### ISSUE TITLE
bug in retrieve species by taxon & country

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#115]
query is "http://phylo.cs.nmsu.edu:5004/phylotastic_ws/ts/country_species?taxon=Arachnida&country=Nepal"

returns error 500 with traceback: 

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "Phylotastic_UI_WebServices_Running.py", line 133, in country_species
    service_result = taxon_to_species_service.get_country_species(taxon, country)
  File "/var/web_service/Phylotastic_UI_WebServices/support/taxon_to_species_service.py", line 131, in get_country_species
    species_list.sort()
UnboundLocalError: local variable 'species_list' referenced before assignment

**Comment by abusalehmdtayeen** [comment]
Thanks Arlin. I know why this error occurred. I will fix it.
